name: release

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for release"
        required: true

jobs:
  relase-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update rust
        run: rustup update

      - name: Compress
        shell: pwsh
        run: |
          cargo build --release
          Compress-Archive ./target/release/melody.exe ./melody-windows.zip

      - uses: actions/upload-artifact@v3
        with:
          name: melody-windows
          path: ./melody-windows.zip
          retention-days: 1
  
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update rust
        run: rustup update
      
      - name: Compress
        run: |
          cargo build --release
          tar -czf ./melody-linux.tar.gz ./target/release/melody

      - uses: actions/upload-artifact@v3
        with:
          name: melody-linux
          path: ./melody-linux.tar.gz
          retention-days: 1

  release-macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3

      - name: Update rust
        run: rustup update
      
      - name: Compress
        run: |
          cargo build --release
          zip -r ./melody-macos.zip ./target/release/melody

      - uses: actions/upload-artifact@v3
        with:
          name: melody-macos
          path: ./melody-macos.zip
          retention-days: 1
  publish:
    needs: [release-windows,release-linux,release-macos]
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GH_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3

      - name: Show downloads
        run: ls 

      - name: Publish binaries
        # Delete --draft
        run: |
            gh release create ${{inputs.tag_name}} --title "${{inputs.tag_name}}" --draft  flow-macos/* flow-linux/* flow-windows/*